org.gradle.jvmargs=-Xmx384m -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=64m -Xss512k -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.caching=true
org.gradle.daemon=false
kotlin.compiler.execution.strategy=in-process

android.useAndroidX=true
android.nonTransitiveRClass=true
android.dexingNumberOfBuckets=1

kotlin.code.style=official
